"""Auto-generated suffix lookup table - DO NOT EDIT"""

SUFFIX_LOOKUP = {
    ('D342X', False, False, False, 'UNKNOWN', 'EPDM', 'NO_DRIVE'): "",
    ('D342X', False, False, False, 'UNKNOWN', 'EPDM', 'UNKNOWN'): "",
    ('D343X', False, False, False, 'UNKNOWN', 'EPDM', 'UNKNOWN'): "",
    ('D41X', False, False, False, 'DI', 'EPDM', 'GEAR'): "4",
    ('D41X', False, False, False, 'DI', 'EPDM', 'LEVER'): "4",
    ('D41X', False, False, False, 'DI', 'EPDM', 'MOTORIZED'): "4",
    ('D41X', False, False, False, 'DI', 'EPDM', 'NO_DRIVE'): "4",
    ('D41X', False, False, False, 'DI', 'EPDM', 'UNKNOWN'): "4",
    ('D41X', False, False, False, 'SS304', 'EPDM', 'GEAR'): "-R4",
    ('D41X', False, False, False, 'SS304', 'EPDM', 'LEVER'): "4",
    ('D41X', False, False, False, 'SS316', 'EPDM', 'GEAR'): "4",
    ('D41X', False, False, False, 'UNKNOWN', 'EPDM', 'GEAR'): "3-16QB1",
    ('D41X', False, False, False, 'UNKNOWN', 'EPDM', 'LEVER'): "4",
    ('D71F', False, False, False, 'SS304', 'PTFE', 'LEVER'): "4",
    ('D71F', False, False, False, 'SS316', 'PTFE', 'LEVER'): "4",
    ('D71F', True, False, False, 'SS304', 'PTFE', 'GEAR'): "LV4",
    ('D71H', True, False, False, 'CS', 'CS', 'GEAR'): "L",
    ('D71X', False, False, False, 'DI', 'EPDM', 'GEAR'): "4",
    ('D71X', False, False, False, 'DI', 'EPDM', 'LEVER'): "K",
    ('D71X', False, False, False, 'DI', 'EPDM', 'NO_DRIVE'): "V4",
    ('D71X', False, False, False, 'DI', 'EPDM', 'UNKNOWN'): "4",
    ('D71X', False, False, False, 'DI', 'NBR', 'GEAR'): "4",
    ('D71X', False, False, False, 'DI', 'NBR', 'LEVER'): "4",
    ('D71X', False, False, False, 'DI_EPDM', 'EPDM', 'GEAR'): "",
    ('D71X', False, False, False, 'SS304', 'EPDM', 'GEAR'): "4",
    ('D71X', False, False, False, 'SS304', 'EPDM', 'LEVER'): "K",
    ('D71X', False, False, False, 'SS304', 'EPDM', 'NO_DRIVE'): "4",
    ('D71X', False, False, False, 'SS304', 'EPDM', 'UNKNOWN'): "S4",
    ('D71X', False, False, False, 'SS304', 'NBR', 'GEAR'): "4",
    ('D71X', False, False, False, 'SS304', 'NBR', 'LEVER'): "4",
    ('D71X', False, False, False, 'SS316', 'EPDM', 'GEAR'): "4",
    ('D71X', False, False, False, 'SS316', 'EPDM', 'LEVER'): "4",
    ('D71X', False, False, False, 'SS316', 'EPDM', 'UNKNOWN'): "4",
    ('D71X', False, False, False, 'SS316', 'NBR', 'GEAR'): "V4",
    ('D71X', False, False, False, 'SS316', 'NBR', 'LEVER'): "4",
    ('D71X', False, False, False, 'SS316', 'VITON', 'LEVER'): "K",
    ('D71X', False, False, False, 'UNKNOWN', 'EPDM', 'GEAR'): "L",
    ('D71X', False, False, False, 'UNKNOWN', 'EPDM', 'LEVER'): "KS",
    ('D71X', False, False, False, 'UNKNOWN', 'EPDM', 'UNKNOWN'): "4",
    ('D71X', False, False, False, 'UNKNOWN', 'NBR', 'LEVER'): "4",
    ('D71X', False, False, False, 'UNKNOWN', 'NBR', 'UNKNOWN'): "V4",
    ('D71X', False, False, True, 'DI', 'EPDM', 'LEVER'): "K",
    ('D71X', False, True, False, 'SS316', 'EPDM', 'LEVER'): "4",
    ('D71X', False, True, False, 'SS316', 'VITON', 'LEVER'): "4",
    ('D71X', True, False, False, 'DI', 'EPDM', 'GEAR'): "L4",
    ('D71X', True, False, False, 'DI', 'EPDM', 'LEVER'): "L4",
    ('D71X', True, False, False, 'DI', 'EPDM', 'MOTORIZED'): "LV4",
    ('D71X', True, False, False, 'DI', 'EPDM', 'UNKNOWN'): "LV4",
    ('D71X', True, False, False, 'DI', 'NBR', 'GEAR'): "L4",
    ('D71X', True, False, False, 'DI', 'NBR', 'LEVER'): "L4",
    ('D71X', True, False, False, 'SS304', 'EPDM', 'GEAR'): "LV4",
    ('D71X', True, False, False, 'SS304', 'EPDM', 'LEVER'): "LV4",
    ('D71X', True, False, False, 'SS304', 'EPDM', 'NO_DRIVE'): "LV26-AS",
    ('D71X', True, False, False, 'SS304', 'EPDM', 'UNKNOWN'): "LV4",
    ('D71X', True, False, False, 'SS304', 'NBR', 'GEAR'): "LV4",
    ('D71X', True, False, False, 'SS304', 'NBR', 'LEVER'): "LV4",
    ('D71X', True, False, False, 'SS304', 'NBR', 'UNKNOWN'): "LV4",
    ('D71X', True, False, False, 'SS316', 'EPDM', 'GEAR'): "LV4",
    ('D71X', True, False, False, 'SS316', 'EPDM', 'LEVER'): "L4",
    ('D71X', True, False, False, 'SS316', 'NBR', 'GEAR'): "L4",
    ('D71X', True, False, False, 'SS316', 'NBR', 'LEVER'): "LV4",
    ('D71X', True, False, False, 'SS316', 'VITON', 'GEAR'): "LV4",
    ('D71X', True, False, False, 'SS316', 'VITON', 'LEVER'): "LV4",
    ('D71X', True, False, False, 'UNKNOWN', 'EPDM', 'GEAR'): "L",
    ('D71X', True, False, False, 'UNKNOWN', 'EPDM', 'LEVER'): "L4",
    ('D71X', True, False, False, 'UNKNOWN', 'EPDM', 'NO_DRIVE'): "LV26-AS",
    ('D71X', True, False, False, 'UNKNOWN', 'EPDM', 'UNKNOWN'): "L",
    ('D71X', True, False, False, 'UNKNOWN', 'NBR', 'LEVER'): "L4",
    ('D71X', True, False, False, 'UNKNOWN', 'NBR', 'UNKNOWN'): "L4",
    ('D71X', True, False, True, 'SS316', 'EPDM', 'LEVER'): "LK",
    ('D71X', True, True, False, 'SS316', 'EPDM', 'LEVER'): "LV4",
    ('D71X', True, True, False, 'SS316', 'NBR', 'LEVER'): "LV4",
    ('D72X', False, False, False, 'UNKNOWN', 'EPDM', 'UNKNOWN'): "C",
    ('D72X', True, False, False, 'UNKNOWN', 'EPDM', 'NO_DRIVE'): "4",
    ('D81F', False, False, False, 'SS316', 'PTFE', 'UNKNOWN'): "700",
    ('D81X', False, False, False, 'DI_EPDM', 'EPDM', 'GEAR'): "4",
    ('D81X', False, False, False, 'DI_EPDM', 'EPDM', 'LEVER'): "4",
    ('D81X', False, False, False, 'DI_EPDM', 'EPDM', 'MOTORIZED'): "4",
    ('D81X', False, False, False, 'DI_EPDM', 'EPDM', 'NO_DRIVE'): "4",
    ('D81X', False, False, False, 'DI_NBR', 'NBR', 'GEAR'): "4-BL",
    ('D81X', False, False, False, 'DI_NBR', 'NBR', 'LEVER'): "E",
    ('D81X', False, False, False, 'DI_NBR', 'NBR', 'UNKNOWN'): "4",
    ('D81X', False, False, False, 'SS316', 'EPDM', 'LEVER'): "702",
    ('D81X', False, False, False, 'SS316', 'NBR', 'LEVER'): "700",
    ('D81X', False, False, False, 'UNKNOWN', 'EPDM', 'GEAR'): "S4",
    ('D81X', False, False, False, 'UNKNOWN', 'EPDM', 'LEVER'): "4",
    ('D81X', False, False, False, 'UNKNOWN', 'EPDM', 'UNKNOWN'): "",
    ('D81X', False, False, True, 'DI_EPDM', 'EPDM', 'LEVER'): "E",
    ('D81X', False, False, True, 'DI_NBR', 'NBR', 'LEVER'): "E",
    ('XD311X', False, False, False, 'DI', 'EPDM', 'UNKNOWN'): "",
    ('XD311X', False, False, False, 'UNKNOWN', 'EPDM', 'MOTORIZED'): "",
    ('XD311X', False, False, False, 'UNKNOWN', 'EPDM', 'UNKNOWN'): "",
    ('XD371X', False, False, False, 'DI', 'EPDM', 'UNKNOWN'): "4",
    ('XD371X', False, False, False, 'DI', 'NBR', 'UNKNOWN'): "243",
    ('XD371X', False, False, False, 'DI_EPDM', 'EPDM', 'GEAR'): "",
    ('XD371X', False, False, False, 'DI_EPDM', 'EPDM', 'UNKNOWN'): "",
    ('XD371X', False, False, False, 'UNKNOWN', 'EPDM', 'GEAR'): "G",
    ('XD371X', False, False, False, 'UNKNOWN', 'EPDM', 'UNKNOWN'): "",
    ('XD371X', True, False, False, 'DI', 'EPDM', 'GEAR'): "L",
    ('XD371X', True, False, False, 'DI_EPDM', 'EPDM', 'GEAR'): "L",
    ('XD371X', True, False, False, 'DI_EPDM', 'EPDM', 'UNKNOWN'): "L",
    ('XD371X', True, False, False, 'UNKNOWN', 'EPDM', 'GEAR'): "L",
    ('XD371X', True, False, False, 'UNKNOWN', 'EPDM', 'UNKNOWN'): "L",
    ('XD381X', False, False, False, 'DI_EPDM', 'EPDM', 'GEAR'): "",
    ('XD381X', False, False, False, 'DI_EPDM', 'EPDM', 'MOTORIZED'): "4",
    ('XD381X', False, False, False, 'DI_EPDM', 'EPDM', 'UNKNOWN'): "",
    ('XD381X', False, False, False, 'DI_EPDM', 'NBR', 'UNKNOWN'): "242",
    ('XD381X', False, False, False, 'UNKNOWN', 'EPDM', 'GEAR'): "E",
    ('XD381X', False, False, False, 'UNKNOWN', 'EPDM', 'UNKNOWN'): "",
    ('XD381X', False, False, False, 'UNKNOWN', 'NBR', 'GEAR'): "E",
}

SUFFIX_LOOKUP_BASE = {
    "D342X": "",
    "D343X": "",
    "D41X": "4",
    "D71F": "4",
    "D71H": "L",
    "D71X": "4",
    "D72X": "4",
    "D81F": "700",
    "D81X": "4",
    "XD311X": "",
    "XD371X": "L",
    "XD381X": "",
}